### ISSUE TITLE
Remove animation or make it faster

### ISSUE THREAD

**Issue by jenstornell** [distantnative/field-switch#8]
The danger of adding an animation is that it can feel slow. I suggest to speed it up or remove it.

I've tried it for the first time today. Really nice.

**Comment by distantnative** [comment]
Hmm, I would agree in a lot of cases. But since this is a simple toggle, you would only click at it once to change its state and then move on. So why would it really matter how fast the animation is?

**Comment by jenstornell** [comment]
Both yes and no.

>you would only click at it once

While this is correct you may have 20 switches on one page and the state may change many times depending on what the field is for.

>So why would it really matter how fast the animation is?

In real life it does not matter. It's the human feeling. Much like the slideshow on this page:

https://getkirby.com/

By choosing not to have an animation in the slideshow it feels lightning fast. In real life it would probably not matter it it takes 0.3 sec or not.

Another reason is that the animation reveal that it's not a built in field. Built in fields feels fast because they don't have animations.

But it's up to you ofcource. :)

**Comment by distantnative** [comment]
I do not really agree and think your comparison is off: The crucial difference with e.g. the getkirby.com slideshow is that while a translation would take place, the user might feel stopped from moving on because he already wants to click again to go on to another slide but feels like he can't because the first animation is still going on. That of course is bad.

With the switch field, you have a toggle. If you want to change it, you do it once and then save it. You might do it on 20 switches on one page but the animation of one switch doesn't stop you from already changing the next switch. It would only if you toggle one switch field multiple times without saving (in under .3s) – and that use case is mainly when you are playing around. I will cut down the animation time to .1s in the next dot release.

And I think it fits in quite well. It doesn't need to hide that it is not a built-in field. It isn't.

**Comment by jenstornell** [comment]
+1
